# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
# default: &default
#   adapter: postgresql
#   encoding: utf8
#   pool: 5
#   username: root
#   password:
#   host: localhost

# development:
#   <<: *default
#   database: User_Auth_development

# test:
#   <<: *default
#   database: User_Auth_test


# production:
#   <<: *default
#   database: User_Auth_production
#   username: User_Auth
#   password: <%= ENV['USER_AUTH_DATABASE_PASSWORD'] %>
development:
  adapter: postgresql
  database: User_Auth_development
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: User_Auth_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: User_Auth_production
  host: localhost  
  pool: 5
  timeout: 5000